spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    mysql-datasource1:
      url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    mysql-datasource2:
      url: jdbc:mysql://192.168.136.201:3306/common?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 1
      max-active: 20
  #    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#    open: true
#    timeout: 6000ms
#    cluster:
#      max-redirects: 3
#      nodes:
#        - 192.168.136.201:6379
    port: 6379
    host: 127.0.0.1
    connect-timeout: 6000
    password:

    lettuce:
      pool:
        max-wait: -1s
        min-idle: 5
        max-idle: 10
        max-active: 1000
  main:
    allow-circular-references: true
  elasticsearch:
    rest:
      uris: localhost:9200
#    password:
#    uris: localhost:9200
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



thread:
  pool:
    core: 16
    maxPoolSize: 32
    keepAliveSeconds: 60
    queueCapacity: 100