spring:
  profiles:
    active: config
  application:
    name: common
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


server:
  port: 8081
  servlet:
    context-path: /common
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,text/csv,application/javascript,application/json,application/xml
    min-response-size: 1024

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  config: classpath:log4j2.yaml