spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    mysql-datasource1:
      url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    mysql-datasource2:
      url: jdbc:mysql://192.168.136.201:3306/common?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 1
      max-active: 20
  #    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#    open: true
#    timeout: 6000ms
#    cluster:
#      max-redirects: 3
#      nodes:
#        - 192.168.136.201:6379
    port: 6379
    host: 127.0.0.1
    connect-timeout: 6000
    password:

    lettuce:
      pool:
        max-wait: -1s
        min-idle: 5
        max-idle: 10
        max-active: 1000
  main:
    allow-circular-references: true
  elasticsearch:
    rest:
      uris: localhost:9200
#    password:
#    uris: localhost:9200
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



thread:
  pool:
    core: 16
    maxPoolSize: 32
    keepAliveSeconds: 60
    queueCapacity: 100


#management:
#  server:
#    port: 8080
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        #默认值访问health,info端点，用*包含全部端点
#        include: "*"
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      show-details: always



car:
  #车况存储配置
  condition-schedule:
    # 一次批量存储数据大小
    batch-size: 10
    # 队列最大值
    max-queue-size: 10000
    # 守护线程检查时间，毫秒
    batch-check-interval: 100
    # redis连接池配置
    jedis-pool-config:
      #最大空闲连接数
      max-idle: 300
      #最大连接数
      max-total: 5000
      #最小空闲连接数
      min-idle: 6
      #最长等待时间
      max-wait-MIIlls: 2000

kafka:
  server: 127.0.0.1:9092
  groupId: baiyan
  order:
    topic: baiyan-test
    concurrent: 3