spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
#    open: true
#    timeout: 6000ms
#    cluster:
#      max-redirects: 3
#      nodes:
#        - 192.168.136.201:6379
    port: 6379
    host: 192.168.136.201
    connect-timeout: 6000
    password: 123456

    lettuce:
      pool:
        max-wait: -1s
        min-idle: 5
        max-idle: 10
        max-active: 1000
  main:
    allow-circular-references: true


server:
  port: 8080
  servlet:
    context-path: /common

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml

pool:
  core: 16
  maxPoolSize: 32
  keepAliveSeconds: 60
  queueCapacity: 100